name: detection
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.8.0
  - readline=7.0
  - setuptools=58.0.4
  - sqlite=3.33.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.12.0
    - astunparse==1.6.3
    - attrs==21.2.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - click==8.0.3
    - colorama==0.4.4
    - cycler==0.11.0
    - cython==0.29.24
    - dill==0.3.4
    - dm-tree==0.1.6
    - flask==2.0.2
    - flask-cors==3.0.10
    - flatbuffers==2.0
    - fonttools==4.28.3
    - future==0.18.2
    - gast==0.4.0
    - gin-config==0.5.0
    - google-api-core==2.2.2
    - google-api-python-client==2.32.0
    - google-auth==2.3.3
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.53.0
    - grpcio==1.42.0
    - h5py==3.6.0
    - httplib2==0.20.2
    - idna==3.3
    - importlib-metadata==4.8.2
    - importlib-resources==5.4.0
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - kaggle==1.5.12
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - libclang==12.0.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - numpy==1.21.4
    - oauth2client==4.1.3
    - oauthlib==3.1.1
    - opencv-python-headless==4.5.4.60
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.4
    - pillow==8.4.0
    - portalocker==2.3.2
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.8.0
    - py-cpuinfo==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - python-slugify==5.0.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sacrebleu==2.0.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - sentencepiece==0.1.96
    - seqeval==1.2.2
    - setuptools-scm==6.3.2
    - six==1.16.0
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.7.0
    - tensorflow-addons==0.15.0
    - tensorflow-datasets==4.4.0
    - tensorflow-estimator==2.7.0
    - tensorflow-hub==0.12.0
    - tensorflow-io-gcs-filesystem==0.22.0
    - tensorflow-metadata==1.5.0
    - tensorflow-model-optimization==0.7.0
    - tensorflow-text==2.7.3
    - termcolor==1.1.0
    - text-unidecode==1.3
    - tf-models-official==2.7.0
    - tf-slim==1.1.0
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - tqdm==4.62.3
    - typeguard==2.13.2
    - typing-extensions==4.0.1
    - uritemplate==4.1.1
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - wrapt==1.13.3
    - zipp==3.6.0
